# Generated by Django 4.0.4 on 2022-05-12 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comment_App', '0001_initial'),
        ('Reply_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comment_App.comment'),
        ),
    ]
