# Generated by Django 4.0.4 on 2022-05-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reply_App', '0002_reply_reply_user_alter_reply_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply_user',
            new_name='user',
        ),
    ]
